export const ROUTES = {
    LOGIN: 'Login',
    REGISTER: 'Register',
    HOME: 'Home',
    FLASHSALE: 'Flash Sale',
    PRODUCT_DETAIL: 'Product Detail',
    REVIEW: 'Review',
    WRITE_REVIEW: 'Write Review',
    EXPLORE: 'Explore',
    EXPLORE_SEARCH: 'Explore Search',
    CART: 'Cart',
    OFFER: 'Offer',
    ACCOUNT: 'Account',
    SHIP_TO: 'Ship To',
    ADDRESS_SHIP: 'Address Ship',
    PAYMENT: 'Payment',
}