export const ROUTES = {
    LOGIN: 'Login',
    REGISTER: 'Register',
    HOME: 'Home',
    FLASHSALE: 'Flash Sale',
    PRODUCT_DETAIL: 'Product Detail',
    REVIEW: 'Review',
    WRITE_REVIEW: 'Write Review',
    EXPLORE: 'Explore',
    EXPLORE_SEARCH: 'Explore Search',
    CART: 'Cart',
    OFFER: 'Offer',
    ACCOUNT: 'Account',
    SHIP_TO: 'Ship To',
    ADDRESS_SHIP: 'Address Ship',
    PAYMENT: 'Payment',
    CHOOSE_CARD: 'Choose Card',
    ORDER_SUCCESS: 'Order Success',
    PROFILE: 'Profile',
    PROFILE_NAME: 'Name',
    PROFILE_GENDER: 'Gender',
    PROFILE_BIRTH_DAY: 'Birthday',
    PROFILE_EMAIL: 'Email',
    PROFILE_PHONE: 'Phone',
    PROFILE__CHANGE_PASSWORD: 'Change Password',
    PRODUCTS_CATEGORY: 'Products of Category',
    FAVORITE_PRODUCT: 'Favorite Product',
    ORDER_ACCOUNT: 'Order Account',
    NOTIFICATION: 'Notification',
}