import {
    ICCategoryBikini,
    ICCategoryDress,
    ICCategoryHighHeels,
    ICCategoryManPants,
    ICCategoryManShoes,
    ICCategoryManTShirt,
    ICCategoryManUnderWear,
    ICCategoryShirt,
    ICCategorySkirt,
    ICCategoryWomenBag,
    ICCategoryWomenPants,
    ICCategoryWomenTShirt,
    ICCategoryWorkEquipment
} from '../assets/icons/index';
export const DataCategory = [
    { id: 1, image: <ICCategoryShirt />, title: 'Shirt' },
    { id: 2, image: <ICCategoryBikini />, title: 'Bikini' },
    { id: 3, image: <ICCategoryDress />, title: 'Dress' },
    { id: 4, image: <ICCategoryHighHeels />, title: 'High Heels' },
    { id: 5, image: <ICCategoryManPants />, title: 'Man Pants' },
    { id: 6, image: <ICCategoryManShoes />, title: 'Man Shoes' },
    { id: 7, image: <ICCategoryManTShirt />, title: 'Man T Shirt' },
    { id: 8, image: <ICCategoryManUnderWear />, title: 'Man Under Wear' },
    { id: 9, image: <ICCategorySkirt />, title: 'Skirt' },
    { id: 10, image: <ICCategoryWomenBag />, title: 'Women Bag' },
    { id: 11, image: <ICCategoryWomenPants />, title: 'Women Pants' },
    { id: 12, image: <ICCategoryWomenTShirt />, title: 'Women T Shirt' },
    { id: 13, image: <ICCategoryWorkEquipment />, title: 'Work Equipment' },
]